services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ib\Ibcontent\:
        resource: "../Classes/*"

    Ib\Ibcontent\Command\ConvertFlexformReferencesForTypo310Command:
        tags:
            - name: "console.command"
              command: "ibcontent:convertflexformreferences"
              description: "V10 - Convert Flexform References"

    Ib\Ibcontent\Command\CleanFlexformDataCommand:
        tags:
            - name: "console.command"
              command: "ibcontent:cleanflexformdatacommand"
              description: "V11 - Clean up flexform data"

    Ib\Ibcontent\Command\ConvertProcessedImagePathsCommand:
        tags:
            - name: "console.command"
              command: "ibcontent:convertprocessedimagepathscommand"
              description: "V12 - Convert Processed Image Paths to real paths"

    Ib\Ibcontent\EventListener\AfterFlexFormDataStructureParsedEventListener:
        tags:
            - name: event.listener
              identifier: "ibcontent.parse_data_structure_listener"
              event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent

    Ib\Ibcontent\Command\ConvertFlexformFileReferencesForTypo312Command:
        tags:
            - name: "console.command"
              command: "ibcontent:convertflexformfilereferencesfortypo312command"
              description: "v12 - convert flexform image file references"
