base: 'https://ib-dippegugger.de/'
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=4649'
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-DE
    direction: ltr
    flag: de
    solr_core_read: core_de
    languageId: 0
  -
    title: en
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_EN.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en-EN
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: gb
    languageId: 1
rootPageId: 4642
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-Agent: *\r\nDisallow: /index.php?id=1986\r\nDisallow: /index.php?id=1987\r\nDisallow: /index.php?id=1986/\r\nDisallow: /index.php?id=1987/\r\nDisallow: /ib-stellen-intern\r\nDisallow: /ib-stellen-intern/\r\nDisallow: /ib-gruppe/stellenboerse-intern/\r\nDisallow: /ib-gruppe/stellenboerse-intern\r\nDisallow: /ib-gruppe/stellenboerse-intern/jobdetails/\r\nDisallow: /fileadmin/user_upload/storage_ib_redaktion/P_und_P_Newsletter/\r\n\r\nUser-agent: SemrushBot\r\nDisallow: /\r\n\r\nSitemap: https://ib-dippegugger.de/sitemap.xml\r\nSitemap: https://ib-dippegugger.de/en/sitemap.xml"
websiteTitle: ''
imports:
  - { resource: "EXT:ib_template/Configuration/siteconfig/global.yaml" }
  - { resource: "EXT:ib_template/Configuration/siteconfig/solr.yaml" }
