<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ib_contact_person"
 *
 * Auto generated by Extension Builder 2016-09-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

declare(strict_types=1);

$_EXTKEY = 'ib_contact_person';

$EM_CONF[$_EXTKEY] = array(
    'title' => 'IB Contact Person',
    'description' => 'plugin to manage the contact persons of IB',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '11.5.0-12.5.99',
            'vhs' => '3.0.1',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
