base: 'https://sozialassistenz-berlin.de/'
baseVariants: {  }
disableStaticFileCache: false

languages:
  -
    title: deutsch
    enabled: true
    base: 'https://sozialassistenz-berlin.de/'
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
    solr_core_read: core_de
    languageId: '0'
rootPageId: 3898
routes: {  }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734
imports:
  - { resource: "EXT:ib_template/Configuration/siteconfig/global.yaml" }
  - { resource: "EXT:ib_template/Configuration/siteconfig/solr.yaml" }

errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=3909'