rootPageId: 1481
base: "https://ib-berlin.de"
baseVariants:
  -
    base: 'https://ib-berlin.ddev.site/'
    condition: 'getenv("IS_DDEV_PROJECT") == "true"'
languages:
  - title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: ""
    hreflang: ""
    direction: ""
    flag: de
    solr_core_read: core_de

routes: {}
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734

  Fwdjobs:
    type: Plugin
    limitToPages:
      - 1957
    routePath: "/{jid}"
    namespace: tx_ibcontent

  IbcontentExtensionProducts:
    type: Plugin
    limitToPages:
      - 1490
    namespace: tx_ibcontent
    routePath: "/{aid}"

  IbcontentExtensionLocations:
    type: Plugin
    limitToPages:
      - 1489
    namespace: tx_ibcontent
    routePath: "/{lid}"
  News:
    type: Extbase
    limitToPages:
      - 1488
      - 2551
    extension: News
    plugin: Pi1
    routes:
      - routePath: "/article/{news-title}"
        _controller: "News::detail"
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
imports:
  - { resource: "EXT:ib_template/Configuration/siteconfig/global.yaml" }
  - { resource: "EXT:ib_template/Configuration/siteconfig/solr.yaml" }

errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=413'