rootPageId: 129
base: "https://ib-freiwilligendienste.de/"
baseVariants:
  - base: 'https://ib-freiwilligendienste.ddev.site'
    condition: 'getenv("IS_DDEV_PROJECT") == "true"'
  - base: 'https://ibfreiwilligendienste2016.rmsdev.de/'
    condition: 'getenv("SITECONFIG_ENV") == "IBSTAGING"'
languages:
  - title: Deutsch
    enabled: true
    languageId: "0"
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ""
    flag: de
    solr_core_read: core_ib_freiwilligendienste_de

routes: {}
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734
  Fwdjobs:
    type: Plugin
    limitToPages:
      - 545
    routePath: "/{jid}"
    namespace: tx_ibcontent
  IbForeignjobs:
    type: Plugin
    limitToPages:
      - 5315
    routePath: '/{fjid}'
    namespace: tx_ibcontent
  IbcontentExtensionProducts:
    type: Plugin
    limitToPages:
      - 492
    namespace: tx_ibcontent
    routePath: "/{aid}"
  IbcontentExtensionLocations:
    type: Plugin
    limitToPages:
      - 493
    namespace: tx_ibcontent
    routePath: "/{lid}"
  News:
    type: Extbase
    limitToPages:
      - 130
    extension: News
    plugin: Pi1
    routes:
      - routePath: "/article/{news-title}"
        _controller: "News::detail"
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
imports:
  - { resource: "EXT:ib_template/Configuration/siteconfig/global.yaml" }
  - { resource: "EXT:ib_template/Configuration/siteconfig/solr.yaml" }

errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=419'