base: 'https://juniti.app/'
disableStaticFileCache: false
friendlycaptcha_js_path: 'EXT:friendlycaptcha_official/Resources/Public/JavaScript/lib/widget-0.9.12.min.js'
friendlycaptcha_puzzle_url: 'https://eu-api.friendlycaptcha.eu/api/v1/puzzle'
friendlycaptcha_secret_key: ''
friendlycaptcha_site_key: ''
friendlycaptcha_verify_url: 'https://eu-api.friendlycaptcha.eu/api/v1/siteverify'
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: DE
    hreflang: de-de
    direction: ltr
    flag: de
    solr_core_read: core_de
    languageId: 0
rootPageId: 7031
solr_enabled_read: true
solr_host_read: ib-solr.rm-solutions.de
solr_path_read: /solr/
solr_port_read: '443'
solr_scheme_read: https
solr_use_write_connection: false
websiteTitle: 'Juniti App'
