# EXT:my_ext/Configuration/RTE/Default.yaml
imports:
  # Import default RTE config (for example)
  - { resource: "EXT:ib_template/Configuration/RTE/Settings/linkBrowser.yaml" }
  - { resource: "EXT:ib_template/Configuration/RTE/Settings/custom.yaml" }
  # Import the image plugin configuration
  - { resource: "EXT:rte_ckeditor_image/Configuration/RTE/Plugin.yaml" }
