base: 'https://ib-jmd.de/'
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=3942'
languages:
  -
    title: deutsch
    enabled: true
    base: 'https://ib-jmd.de/'
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
    solr_core_read: core_de
    languageId: 0
    websiteTitle: ''
rootPageId: 3931
websiteTitle: ''
routes: {}
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734
  IbcontentExtensionProducts:
    type: Plugin
    limitToPages:
      - 5489
    namespace: tx_ibcontent
    routePath: '/{aid}'
  IbcontentExtensionLocations:
    type: Plugin
    limitToPages:
      - 5488
    namespace: tx_ibcontent
    routePath: '/{lid}'
imports:
  - { resource: "EXT:ib_template/Configuration/siteconfig/global.yaml" }
  - { resource: "EXT:ib_template/Configuration/siteconfig/solr.yaml" }
