base: 'https://project-value.eu/'
baseVariants:
  - base: 'https://ib-project-value.rmsdev.de/'
    condition: 'getenv("SITECONFIG_ENV") == "IBSTAGING"'
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=4162'
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-DE
    direction: ''
    flag: de
    solr_core_read: core_de
    languageId: 0
    websiteTitle: ''
  -
    title: en
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_GB.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en-GB
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: gb
    languageId: 1
    solr_core_read: core_en
    websiteTitle: ''
  -
    title: Slowenisch
    enabled: true
    base: /sl/
    typo3Language: sl
    locale: sl_SI.UTF-8
    iso-639-1: sl
    navigationTitle: SL
    hreflang: sl-SI
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: si
    languageId: 5
    solr_core_read: core_generic
    websiteTitle: ''
rootPageId: 4152
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734
  News:
    type: Extbase
    limitToPages:
      - 4432
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/article/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-Agent: *\r\nDisallow: /index.php?id=1986\r\nDisallow: /index.php?id=1987\r\nDisallow: /index.php?id=1986/\r\nDisallow: /index.php?id=1987/\r\nDisallow: /ib-stellen-intern\r\nDisallow: /ib-stellen-intern/\r\nDisallow: /ib-gruppe/stellenboerse-intern/\r\nDisallow: /ib-gruppe/stellenboerse-intern\r\nDisallow: /ib-gruppe/stellenboerse-intern/jobdetails/\r\nDisallow: /fileadmin/user_upload/storage_ib_redaktion/P_und_P_Newsletter/\r\n\r\nUser-agent: SemrushBot\r\nDisallow: /\r\n\r\nSitemap: https://project-value.eu/en/sitemap.xml\r\nSitemap: https://project-value.eu/de/sitemap.xml\r\nSitemap: https://project-value.eu/sl/sitemap.xml"
websiteTitle: ''
imports:
  - { resource: "EXT:ib_template/Configuration/siteconfig/global.yaml" }
  - { resource: "EXT:ib_template/Configuration/siteconfig/solr.yaml" }
