<?php
return [
    'BE' => [
        'adminOnly' => 0,
        'debug' => false,
        'installToolPassword' => '$P$CkHM14MZJCljtdSJ4ARgSd45dLGH1q.',
        'lockSSL' => true,
        'versionNumberInFilename' => '0',
        'warning_email_addr' => $_ENV['WARNING_EMAIL_ADDR'],
        'warning_mode' => '2',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => $_ENV['TYPO3_DB_NAME'],
                'driver' => 'mysqli',
                'host' => $_ENV['TYPO3_DB_HOST'],
                'password' => $_ENV['TYPO3_DB_PASSWORD'],
                'port' => $_ENV['TYPO3_DB_PORT'],
                'user' => $_ENV['TYPO3_DB_USER'],
            ],
        ],
    ],
    'EXT' => [],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
            ],
        ],
    ],
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => '',
            'loginBackgroundImage' => '',
            'loginFootnote' => '',
            'loginHighlightColor' => '',
            'loginLogo' => '',
            'loginLogoAlt' => '',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'fal_securedownload' => [
            'force_download' => '',
            'force_download_for_ext' => '',
            'login_redirect_url' => '',
            'no_access_redirect_url' => '',
            'resumable_download' => '1',
            'track_downloads' => '0',
        ],
        'ib_cmt' => [
            'cmtStoragePid' => '4228',
            'pathRTJSON' => 'https://redaktion.internationaler-bund.de/JSON/cmtExport.json',
            'termsRT' => 'youtube, iframe, script, <style',
            'termsTypo3' => 'youtube, iframe, script',
        ],
        'ib_formbuilder' => [
            'reCaptchaCode' => $_ENV['RECAPTCHA_CODE'],
            'useTestKeys' => '0',
        ],
        'ibcontent' => [
            'emailFrom' => 'noreply@rm-solutions.de',
            'reCaptchaCode' => $_ENV['RECAPTCHA_CODE'],
            'urlIBPdb' => 'https://redaktion.internationaler-bund.de',
            'urlIBPdbImages' => 'https://redaktion.internationaler-bund.de',
            'urlIBPdbInteface' => 'https://redaktion.internationaler-bund.de/api',
            'useTestKeys' => '0',
        ],
        'ibsearch' => [
            'baseDocumentPath' => '//var/www/redaktion.internationaler-bund.de/htdocs/webroot/upload/',
            'baseUrlPath' => 'https://redaktion.internationaler-bund.de/upload/',
            'baseUrlSolrInterface' => 'https://redaktion.internationaler-bund.de/solrsearches/',
        ],
        'mask' => [
            'backend' => 'EXT:ib_template/Resources/Private/Mask/Backend/Templates/',
            'backend_layouts_folder' => '',
            'backendlayout_pids' => '0,1',
            'content' => 'EXT:ib_template/Resources/Private/Mask/Frontend/Templates/',
            'content_elements_folder' => '',
            'json' => 'EXT:ib_template/Resources/Private/Mask/mask.json',
            'layouts' => 'EXT:ib_template/Resources/Private/Mask/Frontend/Layouts/',
            'layouts_backend' => 'EXT:ib_template/Resources/Private/Mask/Backend/Layouts/',
            'loader_identifier' => '',
            'override_shared_fields' => '0',
            'partials' => 'EXT:ib_template/Resources/Private/Mask/Frontend/Partials/',
            'partials_backend' => 'EXT:ib_template/Resources/Private/Mask/Backend/Partials/',
            'preview' => 'EXT:ib_template/Resources/Public/Mask/',
        ],
        'news' => [
            'advancedMediaPreview' => '1',
            'archiveDate' => 'date',
            'categoryBeGroupTceFormsRestriction' => '0',
            'categoryRestriction' => '',
            'contentElementPreview' => '1',
            'contentElementRelation' => '1',
            'dateTimeNotRequired' => '0',
            'hidePageTreeForAdministrationModule' => '0',
            'manualSorting' => '0',
            'mediaPreview' => 'false',
            'pageTreePluginPreview' => '1',
            'prependAtCopy' => '1',
            'resourceFolderImporter' => '/news_import',
            'rteForTeaser' => '0',
            'showAdministrationModule' => '1',
            'showImporter' => '0',
            'slugBehaviour' => 'unique',
            'storageUidImporter' => '1',
            'tagPid' => '1',
        ],
        'recaptcha' => [
            'api_server' => 'https://www.google.com/recaptcha/api.js',
            'enforceCaptcha' => '0',
            'lang' => '',
            'private_key' => $_ENV['RECAPTCHA_PRIVATE_KEY'],
            'public_key' => $_ENV['RECAPTCHA_PUBLIC_KEY'],
            'robotMode' => '0',
            'verify_server' => 'https://www.google.com/recaptcha/api/siteverify',
        ],
        'recordlist_thumbnail' => [
            'list' => 'tx_news_domain_model_news=fal_media',
        ],
        'rte_ckeditor_image' => [
            'fetchExternalImages' => '1',
        ],
        'scheduler' => [
            'maxLifetime' => '1440',
            'showSampleTasks' => '1',
        ],
        'solr' => [
            'allowSelfSignedCertificates' => '0',
            'enableRouteEnhancer' => '0',
            'includeGlobalQParameterInCacheHash' => '0',
            'monitoringType' => '1',
            'pluginNamespaces' => 'tx_solr',
            'useConfigurationFromClosestTemplate' => '0',
            'useConfigurationMonitorTables' => '',
            'useConfigurationTrackRecordsOutsideSiteroot' => '1',
        ],
        'solrfal' => [
            'siteExclusiveRecordTables' => 'pages, pages_language_overlay, tt_content, sys_file_reference, tx_ibgalerie_domain_model_galerie, tx_ibcontactperson_domain_model_contactperson, tx_news_domain_model_news, tx_ibformbuilder_domain_model_form, tx_ibformbuilder_domain_model_emaildata, tx_ibcmt_domain_model_content',
        ],
        'staticfilecache' => [
            'backendDisplayMode' => 'both',
            'boostMode' => '0',
            'cacheTagsEnable' => '0',
            'clearCacheForAllDomains' => '1',
            'cspGenerationOverride' => '0',
            'debugHeaders' => '0',
            'disableInDevelopment' => '0',
            'enableGeneratorBrotli' => '0',
            'enableGeneratorGzip' => '1',
            'enableGeneratorManifest' => '0',
            'enableGeneratorPhp' => '0',
            'enableGeneratorPlain' => '1',
            'hashUriInCache' => '0',
            'htaccessTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Htaccess.html',
            'inlineAssetsFileSize' => '50000',
            'inlineScriptMinify' => '0',
            'inlineServiceFavIcon' => '0',
            'inlineServiceScripts' => '0',
            'inlineServiceStyles' => '0',
            'inlineStyleAssets' => 'ico,png,woff2',
            'inlineStyleMinify' => '0',
            'largeIdentifierInCacheTable' => '0',
            'overrideCacheDirectory' => '',
            'overrideClientUserAgent' => '',
            'phpTemplateName' => 'EXT:staticfilecache/Resources/Private/Templates/Php.html',
            'rawurldecodeCacheFileName' => '0',
            'renameTablesToOtherPrefix' => '0',
            'sendCacheControlHeaderRedirectAfterCacheTimeout' => '0',
            'sendHttp2PushEnable' => '1',
            'sendHttp2PushFileExtensions' => 'css,js',
            'sendHttp2PushFileLimit' => '10',
            'sendHttp2PushLimitToArea' => '',
            'useFallbackMiddleware' => '1',
            'useReverseUriLengthInPriority' => '1',
            'validFallbackHeaders' => 'Content-Type,Content-Language,Link,X-SFC-Tags',
            'validHtaccessHeaders' => 'Content-Type,Content-Language,Link,X-SFC-Tags',
        ],
        'tika' => [
            'excludeMimeTypes' => '',
            'extractor' => 'jar',
            'fileSizeLimit' => '10',
            'javaCommandOptions' => '',
            'logging' => '0',
            'registerMetaDataExtractor' => '1',
            'showTikaSolrModule' => '0',
            'solrCore' => 'core_en',
            'solrHost' => 'ib-solr.rm-solutions.de',
            'solrPassword' => '',
            'solrPath' => '/solr/',
            'solrPort' => '443',
            'solrScheme' => 'https',
            'solrUsername' => '',
            'tikaPath' => $ENV['TIKA_PATH'],
            'tikaServerHost' => '',
            'tikaServerPath' => '',
            'tikaServerPort' => '',
            'tikaServerScheme' => 'http',
        ],
        'vhs' => [
            'disableAssetHandling' => '0',
        ],
    ],
    'FE' => [
        'additionalAbsRefPrefixDirectories' => 'build',
        'cacheHash' => [
            'excludedParameters' => [
                'L',
                'pk_campaign',
                'pk_kwd',
                'utm_source',
                'utm_medium',
                'utm_campaign',
                'utm_term',
                'utm_content',
                'tx_ibcontent[lid]',
                'tx_ibcontent[aid]',
                'tx_ibcontent[jid]',
                'fbclid',
            ],
        ],
        'debug' => false,
        'hidePagesIfNotTranslatedByDefault' => '0',
        'loginRateLimitIpExcludeList' => $ENV['LOGIN_RATE_LIMIT_IP_EXCLUDE_LIST'],
    ],
    'GFX' => [
        'gdlib_png' => false,
        'jpg_quality' => 90,
        'processor' => 'ImageMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'sRGB',
        'processor_effects' => true,
        'processor_enabled' => true,
        'processor_path' => '/usr/bin/',
    ],
    'HTTP' => [],
    'INSTALL' => [],
    'LOG' => [
        'TYPO3' => [
            'CMS' => [
                'deprecations' => [
                    'writerConfiguration' => [
                        'notice' => [
                            'TYPO3\CMS\Core\Log\Writer\FileWriter' => [
                                'disabled' => true,
                            ],
                        ],
                        5 => [
                            'TYPO3\CMS\Core\Log\Writer\FileWriter' => [
                                'disabled' => true,
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    'MAIL' => [
        'defaultMailFromAddress' => 'noreply@rm-solutions.de',
        'defaultMailFromName' => 'IB TYPO3',
        'transport' => 'smtp',
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i',
        'transport_smtp_encrypt' => $_ENV['TYPO3_SMTP_ENCRYPT'] ?: true,
        'transport_smtp_password' => $_ENV['TYPO3_SMTP_PASSWORD'],
        'transport_smtp_server' => $_ENV['TYPO3_SMTP_HOST'],
        'transport_smtp_username' => $_ENV['TYPO3_SMTP_USER'],
    ],
    'SYS' => [
        'UTF8filesystem' => true,
        'belogErrorReporting' => '22517',
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\ApcuBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
                'hash' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                ],
                'imagesizes' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'pages' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
                'rootline' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'options' => [
                        'compression' => true,
                    ],
                ],
            ],
        ],
        'createGroup' => 'apache',
        'devIPmask' => '',
        'displayErrors' => 0,
        'encryptionKey' => '6a005189e1f70f7ffe2b11effadd67369a275652b46c8ed1cdb85571ceb506efb87d8cf29628aa649a9d1d75707b9512',
        'errorHandlerErrors' => '22517',
        'exceptionalErrors' => 4096,
        'features' => [
            'TypoScript.strictSyntax' => false,
            'security.usePasswordPolicyForFrontendUsers' => true,
            'unifiedPageTranslationHandling' => true,
        ],
        'fileCreateMask' => '2775',
        'folderCreateMask' => '2775',
        'mediafile_ext' => 'gif,jpg,jpeg,bmp,png,pdf,svg,ai,mp3,wav,mp4,ogg,flac,opus,webm,youtube',
        'sitename' => $_ENV['TYPO3_SITENAME'] ? : '[V12] Internationaler Bund',
        'systemLocale' => 'de_DE',
    ],
];
