base: 'https://ib-unittest-site-1.rmsdev.de/'
disableStaticFileCache: false
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=5508'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
    solr_core_read: core_de
    websiteTitle: ''
rootPageId: 5498
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734
  IbcontentExtensionProducts:
    type: Plugin
    limitToPages:
      - 39
    namespace: tx_ibcontent
    routePath: '/{aid}'
  IbcontentExtensionLocations:
    type: Plugin
    limitToPages:
      - 40
    namespace: tx_ibcontent
    routePath: '/{lid}'
  News:
    type: Extbase
    limitToPages:
      - 14
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/article/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
websiteTitle: ''
imports:
  - { resource: "EXT:ib_template/Configuration/siteconfig/global.yaml" }
  - { resource: "EXT:ib_template/Configuration/siteconfig/solr.yaml" }
