services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ib\IbCmt\:
        resource: '../Classes/*'

    Ib\IbCmt\Command\CheckContentTagsCommand:
        tags:
            - name: 'console.command'
              command: 'ibcmt:checkcontenttags'
              description: 'V10 - IB CMT check content tags command'
    Ib\IbCmt\Controller\ContentController:
        public: true
        arguments:
            $contentRepository: '@Ib\IbCmt\Domain\Repository\ContentRepository'


