base: 'https://ib-baden.de/'
disableStaticFileCache: false
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: ''
    solr_core_read: core_de
rootPageId: 5814
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
      robots.txt: 84358734
  IbcontentExtensionProducts:
    type: Plugin
    limitToPages:
      - 6165
    namespace: tx_ibcontent
    routePath: '/{aid}'
  IbcontentExtensionLocations:
    type: Plugin
    limitToPages:
      - 6164
    namespace: tx_ibcontent
    routePath: '/{lid}'
  News:
    type: Extbase
    limitToPages:
      - 6252
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/article/{news-title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
    aspects:
      news-title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
websiteTitle: ''
imports:
  -
    resource: 'EXT:ib_template/Configuration/siteconfig/global.yaml'
  -
    resource: 'EXT:ib_template/Configuration/siteconfig/solr.yaml'
